runtime: python311

instance_class: F1

entrypoint: streamlit run app.py

env_variables:
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_SERVER_ENABLE_CORS: "true"
  STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION: "true"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
